class_name Kit
## Runtime loader for the Blender-built asset kit (assets/kit/*.glb,
## generated by tools/blender/make_kit.py). The folder is .gdignore'd, so
## GLTFDocument loads the files directly — no importer, works headless.
## Kit materials are placeholders named in Blender ("bark", "leaves", ...);
## callers pass a {name: Material} map and the mesh comes back rewired, so
## one mesh serves every biome palette.

static var _base := {}
static var _variants := {}


## The raw mesh from assets/kit/<file>.glb (the kit joins each asset into
## a single object). Null when the file is missing or fails to parse —
## callers keep their procedural fallback.
static func base_mesh(file: String) -> Mesh:
	if _base.has(file):
		return _base[file]
	var path := ProjectSettings.globalize_path("res://assets/kit/%s.glb" % file)
	var mesh: Mesh = null
	if FileAccess.file_exists(path):
		var doc := GLTFDocument.new()
		var state := GLTFState.new()
		if doc.append_from_file(path, state) == OK:
			var scene := doc.generate_scene(state)
			var stack: Array = [scene]
			while not stack.is_empty() and mesh == null:
				var n: Node = stack.pop_back()
				if n is MeshInstance3D:
					mesh = n.mesh
				for c in n.get_children():
					stack.append(c)
			scene.free()
	_base[file] = mesh
	return mesh


## A palette variant: the kit mesh with its named placeholder materials
## replaced from `mats`. Cached under `variant`.
static func mesh(file: String, variant: String, mats: Dictionary) -> Mesh:
	var vkey := file + "|" + variant
	if _variants.has(vkey):
		return _variants[vkey]
	var base := base_mesh(file)
	if base == null:
		_variants[vkey] = null
		return null
	var m: Mesh = base.duplicate()
	for si in m.get_surface_count():
		var sm := base.surface_get_material(si)
		var sname := sm.resource_name if sm else ""
		if mats.has(sname):
			m.surface_set_material(si, mats[sname])
	_variants[vkey] = m
	return m
